# Site settings
title: Kai Wu
email: wu.kai2@husky.neu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio page for Kai Wu.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kaii.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Kaaii

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - github-pages
include: ['_pages']

google_analytics: UA-142995398-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
